apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.24.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      smtp_smarthost: 'smtp.feishu.cn:465'       # smtp地址
      smtp_from: 'jiangyixuan@heywhale.com'                # 谁发邮件
      smtp_auth_username: 'jiangyixuan@heywhale.com'       # 邮箱用户
      smtp_auth_password: 'HWs0PAkfJgJrmBo8'                   # 邮箱授权码
      smtp_require_tls: false

    route:
      group_by: ["alertname"]            # 分组名
      group_wait: 10s
      group_interval: 12h                # 发送警告间隔时间
      repeat_interval: 1h              # 重复报警的间隔时间
      receiver: 'default'                # 全局报警组，这个参数是必选的，和下面报警组名要相同

    receivers:
     - name: 'default'
       email_configs:
           - to: 'jiangyixuan@heywhale.com'
type: Opaque
